app/urls.py
from django.urls import path,include
from app import views

app_name='app'

urlpatterns=[
    path('register',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),

]

midas_task/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special',views.special,name='special'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site=models.URLField(blank=True)

    def __str__(self):
        return self.user.username

app/forms.py
from django import forms
from django.contrib.auth.models import User
from app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site',)

app/views.py
from django.shortcuts import render

# Create your views here.

from app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'app/index.html')

@login_required
def special(request):
    return HttpResponse("logged in currently")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()

    # This is the render and context dictionary to feedback to the signup.html file page.
    return render(request,'app/signup.html',
                          {'user_form':user_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check if the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'app/login.html', {})

templates/app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MIDAS IIITD</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
<div class="main">
    <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>Midas IIITD
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'app/logo.jpg' %}" alt="M" height="60px" width="60px"></a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active my-2 mx-sm-2">
                    <a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}">Midas IIITD<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2" ><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'app:register' %}">SignUp</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item active my-2 mx-sm-2"><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item active my-2 mx-sm-2"><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'app:user_login' %}">Login</a></li>
                {% endif %}

                <li class="nav-item active my-2 mx-sm-2" style="color:white">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Home <i class="fas fa-angle-down"></i><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Pages <i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Services <i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Blog <i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Contacts <i class="fas fa-phone"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"><i class="fa fa-search" style="color:blue;float:right;margin-left:14vw"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"><i class="fas fa-bars" style="color:blue;float:right"></i><span class=" sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="container2">
            <div class="box">
                <div id="Indicators" class="carousel" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#Indicators" data-slide-to="0" class="active"></li>
                        <li data-target="#Indicators" data-slide-to="1"></li>
                        <li data-target="#Indicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="im" src="{% static 'app/group.jpg' %}" alt="" height="100%" width="100%">
                        </div>
                        <div class="carousel-item">
                            <img class="im" src="{% static 'app/group1.jpeg' %}" alt="" height="100%" width="102%">
                        </div>
                        <div class="carousel-item">
                            <img class="im" src="{% static 'app/group2.jpeg' %}" alt="" height="100%" width="102%">
                        </div>
                    </div>
                </div>
            </div>
            <div class="box overlay">
                <div class="shape">
                    <div class="container3">
                        <h1 class="one">Web App</h1>
                        <h1 class="one">task</h1>
                        <h4 class="two">Lorem Ipsum is simply dummy text of the
                            printing and typesetting industry.</h4>

                        <a  href="{% url 'app:user_login' %}"><input class="bt" type="submit" style="background:none;color:white;font-size:1vw;border: 1px solid white;padding:0.5vw;margin-top:1vw" value="LOGIN|SIGNUP"></a><a href="">
                        <span style="color:white;margin-top:0;font-size:1vw">
                            <i class='fas fa-chevron-circle-right' style='font-size:2vw;color:white;background:orange;border-radius:50%;font-size:1vw;margin:0.5vw 0 0 0.5vw;'></i>GO TO YOUTUBE</span></a>
                    </div>

                    <div class="dropdown">
                        <button class="dropbtn"><i class="fas fa-caret-down"></i></button>
                        <div class="dropdown-content">
                            <a href="#">Open</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/app/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MIDAS IIITD</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
<!--loads background for the page-->
<style>
body{
  background-image: url("{% static 'app/group.jpg' %}");
  background-repeat: no-repeat;
  background-size: cover;
  background-opacity: 0.3;
}
@media only screen and (min-device-width: 400px) {
  body{
    background-image: url("{% static 'app/group.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
  }
}
</style>

<div class="log">
    <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>Midas IIITD
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'app/logo.jpg' %}" alt="M" height="60px" width="60px"></a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active my-2 mx-sm-2">
                    <a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}">Midas IIITD<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2" ><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'app:register' %}">SignUp</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item active my-2 mx-sm-2"><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item active my-2 mx-sm-2"><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'app:user_login' %}">Login</a></li>
                {% endif %}
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Home <i class="fas fa-angle-down"></i><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Pages<i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Services<i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Blog<i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Contacts<i class="fas fa-phone"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"><i class="fa fa-search" style="color:blue;float:right;margin-left:14vw"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"><i class="fas fa-bars" style="color:blue;float:right"></i><span class=" sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <!--loads frame for login box-->
    <div class="box1">
        <h2>Login</h2>
        <form action="{% url 'app:user_login' %}" method="POST">
            {% csrf_token %}
            <div class="entry">
                <label for="username">Username</label>
                <input type="text" name="username" placeholder="Enter Username" required="">
            </div>
            <div class="entry">
                <label for="password">Password</label>
                <input type="password" name="password" placeholder="Enter Password" required="">
            </div>
            <input type="submit" value="Submit">
        </form>
    </div>

</body>
</html>

templates/app/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MIDAS IIITD</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>

<body>
<!--loads backrgound for signup page-->
<style>
body{
  background-image: url("{% static 'app/group.jpg' %}");
  background-repeat: no-repeat;
  background-size: cover;
  background-opacity: 0.3;
}
@media only screen and (min-device-width: 400px) {
  .body{
    background-image: url("{% static 'app/group.jpg' %}");
    background-repeat: no-repeat;
    background-size: cover;
  }
}
</style>

<div class="sign">
    <nav class="navbar navbar-expand-lg navbar-dark scrolling-navbar">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>Midas IIITD
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'app/logo.jpg' %}" alt="M" height="60px" width="60px"></a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active my-2 mx-sm-2">
                    <a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}">Midas IIITD<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2" ><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'app:register' %}">SignUp</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item active my-2 mx-sm-2"><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item active my-2 mx-sm-2"><a class="nav-link" aria-haspopup="true" aria-expanded="false" href="{% url 'app:user_login' %}">Login</a></li>
                {% endif %}

                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Home <i class="fas fa-angle-down"></i><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Pages<i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Services<i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Blog<i class="fas fa-angle-down"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"> Contacts<i class="fas fa-phone"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"><i class="fa fa-search" style="color:blue;float:right;margin-left:14vw"></i><span class=" sr-only">(current)</span></a>
                </li>
                <li class="nav-item active my-2 mx-sm-2">
                    <a aria-haspopup="true" aria-expanded="false" href="{% url 'index' %}"><i class="fas fa-bars" style="color:blue;float:right"></i><span class=" sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="box2">
        {% if registered %}
        <h1>Thank you for registration</h1>
        {% else %}
        <h2>SignUp</h2>
        <form action="{% url 'app:user_login' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="entry">
                <label>Name</label>
                <input type="text" name="" required="">
            </div>
            <div class="entry">
                <label>Age</label><input type="number" name="" required=""></div>
            <div class="entry">
                <label>Contact Number</label><input type="tel" name="" required=""></div>
            <div class="entry">
                <label>Address</label><input type="text" name="" required=""></div>
            <div class="entry">
                <label>Pincode</label><input type="tel" name="" required=""></div>
            <div class="entry">
                <label>Email ID</label><input type="email" name="" required=""></div>
            <div class="entry">
                <label>Password</label><input type="password" name="" required=""></div>
            <div class="entry">
                <label>Confirm Password</label><input type="password" name="" required=""></div>
            <input type="submit" name="" value="SignUp">
        </form>
        {% endif %}
    </div>

</body>
</html>